In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [4]:
data=pd.read_csv(r"D:\ANN CLASSIFICATION\Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
label_encode_gender=LabelEncoder()
data['Gender']=label_encode_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [7]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder=OneHotEncoder()
geo_encoder=one_hot_encoder.fit_transform(data[['Geography']])
geo_encoder=geo_encoder.toarray()

In [8]:
one_hot_encoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
df=pd.DataFrame(geo_encoder, columns=one_hot_encoder.get_feature_names_out(['Geography']))

In [10]:
data=pd.concat([data.drop(['Geography'],axis=1), df], axis=1)

In [11]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [12]:
with open('label_encode_gender.pkl', 'wb') as file:
    pickle.dump(label_encode_gender, file)
with open('one_hot_encoder.pkl', 'wb') as file:
    pickle.dump(one_hot_encoder, file)

In [13]:
X=data.drop(['Exited'],axis=1)
y=data['Exited']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [14]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [15]:
import tensorflow as tf

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [17]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

d:\ANN CLASSIFICATION\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [18]:
X_train.shape[0]

8000

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [21]:
from tensorflow.keras.callbacks import TensorBoard,EarlyStopping
log_dir="logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)
early_stopping=EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [22]:
history=model.fit(X_train,y_train,validation_split=0.2,epochs=10,batch_size=32,callbacks=[tensorflow_callback,early_stopping])

Epoch 1/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7966 - loss: 0.4562 - val_accuracy: 0.8300 - val_loss: 0.4053
Epoch 2/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8327 - loss: 0.3991 - val_accuracy: 0.8444 - val_loss: 0.3752
Epoch 3/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8553 - loss: 0.3627 - val_accuracy: 0.8562 - val_loss: 0.3548
Epoch 4/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8575 - loss: 0.3484 - val_accuracy: 0.8512 - val_loss: 0.3515
Epoch 5/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8597 - loss: 0.3412 - val_accuracy: 0.8550 - val_loss: 0.3467
Epoch 6/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8603 - loss: 0.3392 - val_accuracy: 0.8581 - val_loss: 0.3443
Epoch 7/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8620 - loss: 0.3338 - val_accuracy: 0.8575 - val_loss: 0.3452
Epoch 8/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8612 - loss: 0.3303 - val_accuracy: 0.8594 - val_loss: 0.3470
Epoch 9/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8637 - loss: 0.3297 - val_accuracy: 0.8569 - val_loss: 0.3437
Epoch 10/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8645 - loss: 0.3277 - val_accuracy: 0.8575 - val_loss: 0.3441

In [23]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [24]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [25]:
%tensorboard --logdir logs

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [26]:
%tensorboard --logdir logs/fit

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [54]:
log_dir = "logs/fit"

In [55]:
%tensorboard --logdir logs/fit

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [50]:
!tensorboard --logdir logs

'tensorboard' is not recognized as an internal or external command,
operable program or batch file.

In [56]:
import sys
print(sys.executable)

d:\ANN CLASSIFICATION\venv\python.exe

In [51]:
%pip install tensorboard

Requirement already satisfied: tensorboard in .\venv\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=0.4 in .\venv\Lib\site-packages (from tensorboard) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in .\venv\Lib\site-packages (from tensorboard) (1.84.0)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard) (3.10.3)
Requirement already satisfied: numpy>=1.12.0 in .\venv\Lib\site-packages (from tensorboard) (2.4.6)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorboard) (26.3)
Requirement already satisfied: pillow in .\venv\Lib\site-packages (from tensorboard) (12.3.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in .\venv\Lib\site-packages (from tensorboard) (7.36.2)
Requirement already satisfied: setuptools>=41.0.0 in .\venv\Lib\site-packages (from tensorboard) (83.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in .\venv\Lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.16.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [52]:
%load_ext tensorboard
%tensorboard --logdir logs

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [57]:
import sys
print(sys.executable)

d:\ANN CLASSIFICATION\venv\python.exe

In [58]:
%pip install tensorboard

Requirement already satisfied: tensorboard in .\venv\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=0.4 in .\venv\Lib\site-packages (from tensorboard) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in .\venv\Lib\site-packages (from tensorboard) (1.84.0)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard) (3.10.3)
Requirement already satisfied: numpy>=1.12.0 in .\venv\Lib\site-packages (from tensorboard) (2.4.6)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorboard) (26.3)
Requirement already satisfied: pillow in .\venv\Lib\site-packages (from tensorboard) (12.3.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in .\venv\Lib\site-packages (from tensorboard) (7.36.2)
Requirement already satisfied: setuptools>=41.0.0 in .\venv\Lib\site-packages (from tensorboard) (83.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in .\venv\Lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.16.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [1]:
%load_ext tensorboard

In [2]:
%tensorboard --logdir logs

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [27]:
import sys
!{sys.executable} -m pip install tensorboard

'd:\ANN' is not recognized as an internal or external command,
operable program or batch file.

In [28]:
import sys
!"{sys.executable}" -m pip install tensorboard

Requirement already satisfied: tensorboard in .\venv\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=0.4 in .\venv\Lib\site-packages (from tensorboard) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in .\venv\Lib\site-packages (from tensorboard) (1.84.0)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard) (3.10.3)
Requirement already satisfied: numpy>=1.12.0 in .\venv\Lib\site-packages (from tensorboard) (2.4.6)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorboard) (26.3)
Requirement already satisfied: pillow in .\venv\Lib\site-packages (from tensorboard) (12.3.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in .\venv\Lib\site-packages (from tensorboard) (7.36.2)
Requirement already satisfied: setuptools>=41.0.0 in .\venv\Lib\site-packages (from tensorboard) (83.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in .\venv\Lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.16.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)

In [29]:
%pip install tensorboard

Requirement already satisfied: tensorboard in .\venv\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=0.4 in .\venv\Lib\site-packages (from tensorboard) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in .\venv\Lib\site-packages (from tensorboard) (1.84.0)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard) (3.10.3)
Requirement already satisfied: numpy>=1.12.0 in .\venv\Lib\site-packages (from tensorboard) (2.4.6)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorboard) (26.3)
Requirement already satisfied: pillow in .\venv\Lib\site-packages (from tensorboard) (12.3.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in .\venv\Lib\site-packages (from tensorboard) (7.36.2)
Requirement already satisfied: setuptools>=41.0.0 in .\venv\Lib\site-packages (from tensorboard) (83.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in .\venv\Lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.16.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [30]:
import tensorboard
print(tensorboard.__version__)

2.21.0

In [31]:
%load_ext tensorboard
%tensorboard --logdir logs

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [ ]:
from tensorboard import program

tb = program.TensorBoard()
tb.configure(argv=[None, "--logdir", "logs"])
url = tb.launch()

print(url)

http://localhost:6006/

WARNING:tensorboard:Deleting accumulator 'fit\\train'
WARNING:tensorboard:Deleting accumulator 'fit\\validation'
WARNING:tensorboard:Deleting accumulator 'fit20260918-145520\\validation'
WARNING:tensorboard:Deleting accumulator 'fit20260918-145520\\train'